if [ -z $ENVSET ]; then
  export PATH=$HOME/.cargo/bin:$HOME/go/bin:/opt/local/bin:/opt/local/sbin:$PATH
  export PATH=/opt/local/Library/Frameworks/Python.framework/Versions/3.14/bin:$PATH
  export ENVSET=1
  . "$HOME/.cargo/env"
fi
